version: '3'                                                                     
services:                                                                        
  app:                                                                           
    build: ./app-logging                                                         
    image: app-logging                                                           
    container_name: app-logging                                                  
    ports:                                                                       
      - 5000:5000                                                                
                                                                                 
  #grafana:                                                                      
    #image: grafana/grafana:latest                                               
    #container_name: grafana                                                     
    #ports:                                                                      
    #  - "3000:3000"                                                             
    #volumes:                                                                    
    #  - grafana-storage:/var/lib/grafana                                        
    #restart: always                                                             
                                                                                 
  loki:                                                                          
    image: grafana/loki:latest                                                   
    container_name: loki                                                         
    restart: always                                                              
    ports:                                                                       
      - 3100:3100                                                                
    volumes:                                                                     
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml                       
      - loki-storage:/loki/data                                                  
                                                                                 
  promtail:                                                                      
    image: grafana/promtail:latest                                               
    container_name: promtail                                                     
    volumes:                                                                     
      - ./promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro    
      - ./promtail/tmp:/tmp                                                      
      - /var/lib/docker/containers:/var/lib/docker/containers:ro                 
      - ./promtail/geolite2-city.mmdb:/etc/promtail/geolite2-city.mmdb:ro        
    command: "-config.file=/etc/promtail/promtail-config.yaml"                   
    restart: always                                                              
                                                                                 
volumes:  
  #grafana-storage:
  loki-storage:                                                                       